"""`weft extract` over the synthetic corpus: what is found, what is written, and what is refused.

The corpus is generated by the fixture rather than read from the committed copy, so a stale commit cannot make a test pass. Nothing here touches the network and nothing compiles: the one test about compiled numbering writes the `.aux` a compile would have left.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from support import extracted, paper
from weft.config import load
from weft.crawl.work import load_all
from weft.extract import ExtractReport, extract_corpus, extract_version
from weft.extract.extract import Refused, find_main
from weft.store.rebuild import rebuild
from weft.store.sqlite import SqliteStore

# What the synthetic corpus's three sourced versions hold: v1 of the first seed states a theorem, a lemma and a proposition; v2 drops the lemma, which renumbers the proposition; the second seed states a theorem and a corollary.
EXPECTED = {
    "arxiv:2401.00001v1": [
        ("thm-1.1", "1.1", ["thm:main"]),
        ("lem-2.1", "2.1", ["lem:support"]),
        ("prop-2.2", "2.2", ["prop:degree"]),
    ],
    "arxiv:2401.00001v2": [("thm-1.1", "1.1", ["thm:main"]), ("prop-2.1", "2.1", ["prop:degree"])],
    "arxiv:2401.00002v1": [("thm-1.1", "1.1", ["thm:vanish"]), ("cor-2.1", "2.1", ["cor:rigid"])],
}


def results_of(corpus: Path, home: str, local: str) -> dict:
    """The `results.json` of one version of the synthetic corpus."""
    return json.loads((corpus / "works" / home / local / "results.json").read_text(encoding="utf-8"))


def run(corpus: Path, **kwargs: object) -> ExtractReport:
    return extract_corpus(load(corpus), **kwargs)  # type: ignore[arg-type]


def test_every_statement_is_extracted_with_its_number_and_aliases(synthetic: Path) -> None:
    report = run(synthetic)
    assert [o.status for o in report.outcomes] == ["extracted"] * 3
    assert report.payload()["results"] == 7

    for home, local, version in (
        ("arxiv/2401.00001", "v1", "arxiv:2401.00001v1"),
        ("arxiv/2401.00001", "v2", "arxiv:2401.00001v2"),
        ("arxiv/2401.00002", "v1", "arxiv:2401.00002v1"),
    ):
        data = results_of(synthetic, home, local)
        assert data["version"] == version
        got = [(r["local"], r["number"], r["aliases"]) for r in data["results"]]
        assert got == EXPECTED[version]
        assert all(r["taxon"] and r["statement"].strip() for r in data["results"])


def test_v2_drops_v1s_lemma_and_renumbers_the_proposition(synthetic: Path) -> None:
    run(synthetic)
    v1 = results_of(synthetic, "arxiv/2401.00001", "v1")["results"]
    v2 = results_of(synthetic, "arxiv/2401.00001", "v2")["results"]

    assert [r["local"] for r in v1] == ["thm-1.1", "lem-2.1", "prop-2.2"]
    assert [r["local"] for r in v2] == ["thm-1.1", "prop-2.1"]
    # the same statement, under two numbers, in two versions: which is why a result belongs to a version and "the same result twice" is a mapping rather than an identity
    proposition = [r for r in v1 if r["local"] == "prop-2.2"][0], [r for r in v2 if r["local"] == "prop-2.1"][0]
    assert proposition[0]["statement"] == proposition[1]["statement"]
    assert proposition[0]["aliases"] == proposition[1]["aliases"] == ["prop:degree"]
    assert not any(r["taxon"] == "Lemma" for r in v2)


def test_proofs_are_kept_under_verbatim(synthetic: Path) -> None:
    run(synthetic)
    results = results_of(synthetic, "arxiv/2401.00001", "v1")["results"]
    assert all(r["proof"].strip() for r in results)
    assert "basis-exchange graph" in [r for r in results if r["local"] == "lem-2.1"][0]["proof"]
    digest = (synthetic / "works/arxiv/2401.00001/v1/digest.tex").read_text(encoding="utf-8")
    assert digest.count("\\begin{proof}") == 3
    assert "% !LOOM proofs: verbatim" in digest


def test_proofs_are_absent_under_none(synthetic: Path) -> None:
    report = run(synthetic, proofs="none")
    assert report.payload()["proofs_kept"] == 0
    results = results_of(synthetic, "arxiv/2401.00001", "v1")["results"]
    assert [r["proof"] for r in results] == ["", "", ""]
    digest = (synthetic / "works/arxiv/2401.00001/v1/digest.tex").read_text(encoding="utf-8")
    assert "\\begin{proof}" not in digest
    assert "% !LOOM proofs: none" in digest
    # the proof is dropped, what it pointed at is not: \uses is read from the proof under either policy
    assert "\\uses{arxiv-2401.00001v1-thm-1.1, arxiv-2401.00001v1-lem-2.1}" in digest


def test_results_json_is_what_rebuild_reads(synthetic: Path, tmp_path: Path) -> None:
    run(synthetic)
    settings = load(synthetic)
    store = SqliteStore(tmp_path / "index.sqlite")
    try:
        counts = rebuild(settings, store)
        assert counts["results"] == 7
        assert counts["edges"] == 0  # the two cross-paper cases are M3's; an empty list is the honest record of that
        got = store.result("arxiv:2401.00001v2#prop-2.1")
        assert got is not None
        assert got.taxon == "Proposition" and got.number == "2.1"
        assert got.aliases == ["prop:degree"]
        assert "minimal valuation" in got.statement and "hyperplane" in got.proof
        assert sorted(r.local for r in store.results_of("arxiv:2401.00001v1")) == ["lem-2.1", "prop-2.2", "thm-1.1"]
    finally:
        store.close()


def test_the_records_version_entry_is_updated(synthetic: Path) -> None:
    run(synthetic)
    record = load_all(synthetic / "works")["arxiv:2401.00001"]
    entries = {v.id: v for v in record.versions}
    assert entries["arxiv:2401.00001v1"].method == "latex"
    assert entries["arxiv:2401.00001v1"].numbering == "emulated"
    assert entries["arxiv:2401.00001v1"].extracted_at
    assert entries["arxiv:2401.00001v2"].extracted_at
    # the record is rewritten whole, so nothing else it held is lost
    assert record.title == "Tropical cycles on fans of valuated matroids"
    assert len(record.references) == 2


def test_a_metadata_only_work_is_not_extracted(synthetic: Path) -> None:
    report = run(synthetic)
    assert "doi:10.4171/synth.0003" not in [o.work for o in report.outcomes]
    assert not (synthetic / "works/doi/10.4171_synth.0003/main/results.json").exists()


def test_a_second_run_leaves_what_is_done_alone_unless_asked(synthetic: Path) -> None:
    run(synthetic)
    again = run(synthetic)
    assert [o.status for o in again.outcomes] == ["done"] * 3
    assert again.payload()["results"] == 0

    redone = run(synthetic, redo=True)
    assert [o.status for o in redone.outcomes] == ["extracted"] * 3


def test_one_work_at_a_time_by_any_of_its_identifiers(synthetic: Path) -> None:
    report = run(synthetic, idents=["doi:10.48550/arxiv.2401.00001"])
    assert {o.version for o in report.outcomes} == {"arxiv:2401.00001v1", "arxiv:2401.00001v2"}
    assert not (synthetic / "works/arxiv/2401.00002/v1/results.json").exists()


def test_a_compiled_number_beats_an_emulated_one(synthetic: Path) -> None:
    src = synthetic / "works/arxiv/2401.00001/v1/src"
    (src / "main.aux").write_text("\\newlabel{thm:main}{{7.3}{9}}\n", encoding="utf-8")
    run(synthetic)
    data = results_of(synthetic, "arxiv/2401.00001", "v1")
    assert data["numbering"] == "compiled"
    first = data["results"][0]
    assert (first["local"], first["number"], first["page"]) == ("thm-7.3", "7.3", "9")
    digest = (synthetic / "works/arxiv/2401.00001/v1/digest.tex").read_text(encoding="utf-8")
    assert (
        "% !LOOM numbering: emulated" not in digest
    )  # §2.9: the directive is there only when the numbers were counted
    assert "\\cite[Theorem 7.3, p.~9]" in digest
    record = load_all(synthetic / "works")["arxiv:2401.00001"]
    assert {v.id: v.numbering for v in record.versions}["arxiv:2401.00001v1"] == "compiled"


def test_a_source_with_no_document_class_is_refused(synthetic: Path, tmp_path: Path) -> None:
    paper(tmp_path / "src", "\\begin{document}\\end{document}\n")
    with pytest.raises(Refused, match="documentclass"):
        find_main(tmp_path / "src")


def test_several_candidate_main_files_are_refused_by_name(tmp_path: Path) -> None:
    body = "\\documentclass{article}\\begin{document}Hello\\end{document}\n"
    paper(tmp_path / "src", body, "one.tex")
    paper(tmp_path / "src", body, "two.tex")
    with pytest.raises(Refused, match="one.tex, two.tex"):
        find_main(tmp_path / "src")


def test_a_main_file_is_the_one_that_opens_the_document(tmp_path: Path) -> None:
    paper(tmp_path / "src", "\\documentclass{article}\n", "preamble.tex")
    paper(tmp_path / "src", "\\documentclass{article}\\begin{document}Hi\\end{document}\n", "paper.tex")
    assert find_main(tmp_path / "src") == "paper.tex"


def test_a_version_whose_source_never_arrived_is_refused_with_the_path(synthetic: Path) -> None:
    settings = load(synthetic)
    record = load_all(settings.works_dir)["doi:10.4171/synth.0003"]
    with pytest.raises(Refused, match="no source unpacked"):
        extract_version(settings, record, record.versions[0])


def test_an_unnumbered_environment_is_numbered_from_one_in_document_order(tmp_path: Path) -> None:
    made = extracted(
        tmp_path / "src",
        "\\documentclass{article}\n\\newtheorem*{remark}{Remark}\n\\newtheorem{theorem}{Theorem}\n"
        "\\begin{document}\n\\begin{remark}\nFirst.\n\\end{remark}\n\\begin{theorem}\nA claim.\n\\end{theorem}\n"
        "\\begin{remark}\nSecond.\n\\end{remark}\n\\end{document}\n",
    )
    assert [s.local for s in made.statements] == ["rem-star-1", "thm-1", "rem-star-2"]


def test_a_prefix_the_record_names_is_used_instead_of_the_derived_one(synthetic: Path) -> None:
    path = synthetic / "works/arxiv/2401.00001/work.json"
    record = json.loads(path.read_text(encoding="utf-8"))
    record["versions"][0]["prefix"] = "kresch v2"
    path.write_text(json.dumps(record, indent=2) + "\n", encoding="utf-8")

    run(synthetic)
    digest = (synthetic / "works/arxiv/2401.00001/v1/digest.tex").read_text(encoding="utf-8")
    assert "% !LOOM prefix: kresch-v2" in digest  # declared, and sanitised to the id grammar of §3.1
    assert "\\label{kresch-v2-thm-1.1}" in digest
    # the version that named none keeps the prefix its identifier gives
    other = (synthetic / "works/arxiv/2401.00001/v2/digest.tex").read_text(encoding="utf-8")
    assert "% !LOOM prefix: arxiv-2401.00001v2" in other


def test_asking_for_a_compile_without_latexmk_falls_back_to_counting(
    synthetic: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    import weft.tex.runner as runner

    monkeypatch.setattr(runner, "which_latexmk", lambda: None)
    report = run(synthetic, compile=True)
    assert {o.numbering for o in report.outcomes} == {"emulated"}
    assert results_of(synthetic, "arxiv/2401.00001", "v1")["numbering"] == "emulated"
