"""Extraction over a real paper, offline: the invariants that hold of any paper, not of one.

`demos/relloc` is a corpus of other people's arXiv sources, gitignored and generated by a crawl, so this is skipped where it has not been fetched. It writes nothing into the corpus -- the extractor is called directly -- and it asserts nothing about what any particular paper says, because a test that pins one author's theorem numbers fails the day the corpus is refetched.
"""

from __future__ import annotations

import re
from dataclasses import replace
from pathlib import Path

import pytest

from support import PROV
from weft.extract.extract import Refused, extract, find_main, read_paper
from weft.extract.write import result_payload
from weft.tex.digests import header, is_digest

CORPUS = Path(__file__).resolve().parents[1] / "demos" / "relloc" / "works"
ID = re.compile(r"[A-Za-z0-9.-]+")


def one_source() -> tuple[Path, str] | None:
    """The first unpacked source of the corpus that names a main file, in a fixed order so the test is the same twice."""
    for src in sorted(p for p in CORPUS.rglob("src") if p.is_dir()):
        try:
            return src, find_main(src)
        except Refused:
            continue
    return None


@pytest.mark.skipif(not CORPUS.is_dir(), reason="demos/relloc has not been fetched")
def test_a_real_paper_extracts_into_well_formed_results() -> None:
    found = one_source()
    if found is None:
        pytest.skip("demos/relloc holds no source with a main file")
    src, main = found
    made = extract(read_paper(src, main), replace(PROV, prefix="paper"))

    assert any(s.statement.strip() for s in made.statements), f"{src}: no result carries a statement"
    assert is_digest(made.digest) and header(made.digest)["proofs"] == "verbatim"

    for s in made.statements:
        ident = f"paper-{s.local}"
        assert ID.fullmatch(ident), f"{ident} is not an id (§3.1)"
        assert s.taxon, f"{ident} has no taxon"
        for field in ("statement", "proof"):
            text = result_payload(s)[field]
            opened, closed = text.count("\\begin{"), text.count("\\end{")
            assert opened == closed, f"{ident}: {field} has {opened} \\begin and {closed} \\end"

    # the file is a document: every environment the digest opens, it closes
    assert made.digest.count("\\begin{") == made.digest.count("\\end{")
