"""Generate docs/cli-reference.md from the click command tree, so the reference and `--help` never disagree.

Usage: uv run python scripts/gen_cli_reference.py [--check]   (--check exits 1 when the checked-in file is stale)
"""

from __future__ import annotations

import inspect
import re
import sys
from pathlib import Path

import click

from weft.cli import main

OUT = Path(__file__).resolve().parent.parent / "docs" / "cli-reference.md"


def _normalise(text: str) -> str:
    """Docstrings keep or lose their indentation depending on the Python version; one space between words makes the output the same everywhere."""
    lines = [re.sub(r"[ \t]+", " ", ln).strip() for ln in inspect.cleandoc(text).splitlines()]
    return "\n".join(lines).strip()


def _usage_line(cmd: click.Command, path: list[str]) -> str:
    ctx = click.Context(cmd, info_name=" ".join(path))
    return " ".join([" ".join(path), *cmd.collect_usage_pieces(ctx)]).strip()


def _render(cmd: click.Command, path: list[str], depth: int, out: list[str]) -> None:
    name = " ".join(path)
    out.append(f"{'#' * min(depth, 4)} `{name}`")
    out.append("")
    out.append(f"`{_usage_line(cmd, path)}`")
    out.append("")
    if cmd.help:
        out.append(_normalise(cmd.help))
        out.append("")
    ctx = click.Context(cmd, info_name=name)
    # the help option is left out: its spelling depends on the context it was first rendered in, and every command has it
    params = [p for p in cmd.get_params(ctx) if isinstance(p, click.Option) and "--help" not in p.opts]
    if params:
        out.append("| option | description |")
        out.append("|---|---|")
        for p in params:
            opts = ", ".join(f"`{o}`" for o in [*p.opts, *p.secondary_opts])
            meta = f" `{p.metavar}`" if p.metavar else ""
            help_text = _normalise(p.help or "").replace("|", "\\|")
            out.append(f"| {opts}{meta} | {help_text} |")
        out.append("")
    if isinstance(cmd, click.Group):
        for sub_name in sorted(cmd.commands):
            sub = cmd.commands[sub_name]
            if sub.name != sub_name:
                continue  # an alias; the command is listed once under its own name
            _render(sub, [*path, sub_name], depth + 1, out)


def generate() -> str:
    out = [
        "# weft command reference",
        "",
        "Generated by `scripts/gen_cli_reference.py` from the command tree; do not edit. Every command reads a corpus at or above the working directory unless `--corpus` names one; only `crawl` touches the network.",
        "",
    ]
    _render(main, ["weft"], 1, out)
    return "\n".join(out).rstrip("\n") + "\n"


if __name__ == "__main__":
    text = generate()
    if "--check" in sys.argv:
        current = OUT.read_text(encoding="utf-8") if OUT.is_file() else ""
        if current != text:
            print(f"{OUT} is stale; run scripts/gen_cli_reference.py")
            sys.exit(1)
        print("cli-reference.md is current")
    else:
        OUT.parent.mkdir(parents=True, exist_ok=True)
        OUT.write_text(text, encoding="utf-8")
        print(f"wrote {OUT}")
