#!/usr/bin/env python3
"""Write `demos/synthetic/`: a small fabricated corpus, in the corpus format of the plan's §4, that the tests use instead of anyone's papers.

Everything in it is invented — the authors, the titles, the mathematics, the identifiers and the URLs — so the corpus can be committed and a test can read verbatim statements without carrying a third party's text. There is no network, no randomness and no clock: run it twice and the bytes are the same, so `git status` after a regeneration is the check that it is still deterministic.

Usage
-----
    uv run python scripts/make_synthetic.py [DEST]

Tests import `write_corpus` and build into a temporary directory rather than reading the committed copy, so a stale commit cannot make a test pass.
"""

from __future__ import annotations

import json
import shutil
import sys
from pathlib import Path
from typing import Any

HERE = Path(__file__).resolve().parent
DEST = HERE.parent / "demos" / "synthetic"

# Fixed, because a generated corpus that changes when the clock moves is not a fixture.
AT = "2026-09-17T12:00:00Z"

WEFT_TOML = """# A fabricated corpus: invented authors, invented mathematics, no third-party text. Generated by scripts/make_synthetic.py; edit that, not this.

[seeds]
works = ["arxiv:2401.00001", "arxiv:2401.00002"]
bib = []

[crawl]
depth = 2
subjects = ["14N"]
categories = ["math.AG"]
cap = 5

[sources]
contact = ""

[store]
dsn = "sqlite:index.sqlite"

[licence]
share = false
"""

# One LaTeX source per version. Each declares its own theorem environments, labels every statement, cites one work with a locator and one without, and inlines its bibliography as a `\\begin{thebibliography}` -- which is what both real seed papers did, and the reason the crawl's unit is the `\\bibitem` and not a file extension.

A_V1 = r"""\documentclass{article}
\newtheorem{theorem}{Theorem}[section]
\newtheorem{lemma}[theorem]{Lemma}
\newtheorem{proposition}[theorem]{Proposition}

\title{Tropical cycles on fans of valuated matroids}
\author{B. Aurelio \and D. Cerny}

\begin{document}
\maketitle

\section{Statements}

\begin{theorem}\label{thm:main}
Let $M$ be a valuated matroid of rank $r$ on a finite ground set $E$. Then the tropical cycle $Z(M)$ is balanced and its recession fan is the Bergman fan of the underlying matroid.
\end{theorem}

\begin{proof}
Balancing is local at a codimension-one cone, so it is enough to check one wall. By \cite[Theorem 2.1]{other} the weighted count across a wall of $Z(M)$ agrees with the local degree of the associated stable map, and that count vanishes exactly when the wall is interior. The identification of the recession fan is then the computation of \cite{third}.
\end{proof}

\section{Consequences}

\begin{lemma}\label{lem:support}
The support of $Z(M)$ is connected in codimension one.
\end{lemma}

\begin{proof}
Two maximal cones meeting a common wall are joined by a path inside the support, and the basis-exchange graph of $M$ is connected.
\end{proof}

\begin{proposition}\label{prop:degree}
The degree of $Z(M)$ equals the number of bases of $M$ of minimal valuation.
\end{proposition}

\begin{proof}
Intersect with a generic translate of the standard hyperplane and apply Theorem~\ref{thm:main} together with Lemma~\ref{lem:support}.
\end{proof}

\begin{thebibliography}{9}
\bibitem{other} F. Ekstrom and H. Gallant, \emph{A vanishing theorem for weighted stable curves}, preprint, 2024, arXiv:2401.00002.
\bibitem{third} J. Ibarra, \emph{Foundations of the synthetic period map}, Lecture notes, 1998.
\end{thebibliography}

\end{document}
"""

# v2 drops Lemma 2.1 of v1, so the Proposition renumbers: the case per-version results exist for.
A_V2 = r"""\documentclass{article}
\newtheorem{theorem}{Theorem}[section]
\newtheorem{proposition}[theorem]{Proposition}

\title{Tropical cycles on fans of valuated matroids}
\author{B. Aurelio \and D. Cerny}

\begin{document}
\maketitle

\section{Statements}

\begin{theorem}\label{thm:main}
Let $M$ be a valuated matroid of rank $r$ on a finite ground set $E$. Then the tropical cycle $Z(M)$ is balanced and its recession fan is the Bergman fan of the underlying matroid.
\end{theorem}

\begin{proof}
Balancing is local at a codimension-one cone, so it is enough to check one wall. By \cite[Theorem 2.1]{other} the weighted count across a wall of $Z(M)$ agrees with the local degree of the associated stable map, and that count vanishes exactly when the wall is interior. The identification of the recession fan is then the computation of \cite{third}.
\end{proof}

\section{Consequences}

\begin{proposition}\label{prop:degree}
The degree of $Z(M)$ equals the number of bases of $M$ of minimal valuation.
\end{proposition}

\begin{proof}
Intersect with a generic translate of the standard hyperplane; connectivity in codimension one is now immediate from Theorem~\ref{thm:main} and the lemma of the first version is not needed.
\end{proof}

\begin{thebibliography}{9}
\bibitem{other} F. Ekstrom and H. Gallant, \emph{A vanishing theorem for weighted stable curves}, preprint, 2024, arXiv:2401.00002.
\bibitem{third} J. Ibarra, \emph{Foundations of the synthetic period map}, Lecture notes, 1998.
\end{thebibliography}

\end{document}
"""

B_V1 = r"""\documentclass{article}
\newtheorem{theorem}{Theorem}[section]
\newtheorem{corollary}[theorem]{Corollary}

\title{A vanishing theorem for weighted stable curves}
\author{F. Ekstrom \and H. Gallant}

\begin{document}
\maketitle

\section{The vanishing}

\begin{theorem}\label{thm:vanish}
Let $C$ be a weighted stable curve of genus $g$ with weights summing to less than one. Then $H^1(C, \omega_C) = 0$.
\end{theorem}

\begin{proof}
The weight condition forces every component to be rational, so the dualising sheaf is a sum of line bundles of negative degree. The vanishing for each summand is the local computation of \cite[Theorem 2.1]{other}, and the compatibility of the two normalisations is the point of \cite{third}.
\end{proof}

\section{A consequence}

\begin{corollary}\label{cor:rigid}
Such a curve admits no infinitesimal automorphism.
\end{corollary}

\begin{proof}
Immediate from Theorem~\ref{thm:vanish} and Serre duality.
\end{proof}

\begin{thebibliography}{9}
\bibitem{other} B. Aurelio and D. Cerny, \emph{Tropical cycles on fans of valuated matroids}, preprint, 2024, arXiv:2401.00001.
\bibitem{third} J. Ibarra, \emph{Foundations of the synthetic period map}, Lecture notes, 1998.
\end{thebibliography}

\end{document}
"""

README = """# demos/synthetic

A fabricated corpus, written by `scripts/make_synthetic.py` and committed. **Nothing in it is real**: the authors, titles, identifiers, URLs and mathematics are invented, so no third party's text is carried here and the whole thing can live in the repository. Regenerate it with

    uv run python scripts/make_synthetic.py

The script is deterministic and idempotent -- fixed dates, no network, no randomness -- so a regeneration that changes a byte is a change in the generator, and `git status` says so.

## What is in it, and what each piece is for

- **`weft.toml`** -- two seed works, `depth = 2`, `subjects = ["14N"]`, `cap = 5`. Exercises settings loading and a depth greater than one with the subjects actually stated.
- **`arxiv:2401.00001`, two versions.** v1 states a theorem, a lemma and a proposition; v2 states the theorem and the proposition and **drops the lemma**, which renumbers the proposition. This is the case the whole per-version data model exists for: results belong to a version, and "the same result in two versions" is a mapping and not an identity.
- **`arxiv:2401.00002`, one version.** The second seed, cited by the first and citing it back, so the citation graph has a cycle and a walk has to cope with one.
- **`doi:10.4171/synth.0003`, metadata-only.** Depth 2, no source and no PDF, reached from both seeds by lookup rather than by a printed identifier. It is the node that is in the citation graph and absent from the result graph, and its key has a slash in the value, which a home sanitises away so one identifier stays one directory.
- **Each version with a source: `works/<home>/<version-local>/src/main.tex`.** `\\newtheorem` declarations to read numbering off, labelled statements, and in every proof one `\\cite[Theorem 2.1]{other}` (a locator citation, §7's first case) and one bare `\\cite{third}` (an unspecified citation, §7's second case).
- **An inlined `\\begin{thebibliography}` in every source**, one `\\bibitem` printing an arXiv id and one printing nothing identifying at all. Both real seed papers inlined their bibliography and 9% of their entries carried a usable identifier; this is that situation in miniature, and it is what the `\\bibitem` parser and the lookup path are tested against.
- **No `results.json` and no PDFs.** Extraction is M2's, so nothing here claims to be extraction output; `rebuild` reads `results.json` when it is there and the tests write one by hand to check that it does.
"""

DEMOS_README = """# demos

Three corpora, one committed and two not.

- **`synthetic/`** -- fabricated, committed, and what the tests read. Invented authors and invented mathematics in the real corpus format: two seeds, a work with two versions differing by a dropped result, a metadata-only work, and a source per version with locator and unspecified citations and an inlined bibliography. Written by `scripts/make_synthetic.py`; see [synthetic/README.md](synthetic/README.md).
- **`acgs/`** -- [arXiv:1709.09864](https://arxiv.org/abs/1709.09864) crawled to depth 2, the first seed corpus of the plan's §13.
- **`relloc/`** -- the relative-localization paper's bibliography at depth 2, the second, which loom has already fetched and measured.

`acgs/` and `relloc/` are **gitignored in full**. They hold other people's papers -- sources, PDFs, and statements and proofs copied verbatim -- and a corpus is private by default (§10). Generate them yourself:

    cd demos/acgs && weft crawl plan && weft crawl fetch

The measurements those two produce -- identification rate by depth, how many works have a source, results per paper, how many `\\cite[locator]` references resolve and the false-match rate in a hand-checked sample -- are the point of them, and they are what decides whether the cross-paper graph is a product or a research project.
"""


def _work_a() -> dict[str, Any]:
    return {
        "record": 1,
        "key": "arxiv:2401.00001",
        "ids": ["arxiv:2401.00001", "doi:10.48550/arxiv.2401.00001"],
        "title": "Tropical cycles on fans of valuated matroids",
        "authors": ["Aurelio, Bram", "Cerny, Dagna"],
        "year": "2024",
        "msc": ["14N35", "14T15"],
        "arxiv_category": "math.AG",
        "licence": "arXiv non-exclusive",
        "depth": 1,
        "reached_from": ["arxiv:2401.00002"],
        "reached_by": "declared",
        "provenance": "declared",
        "citekeys": ["other"],
        "references_known": True,
        "references": [
            {
                "work": "arxiv:2401.00002",
                "citekey": "other",
                "text": "F. Ekstrom and H. Gallant, A vanishing theorem for weighted stable curves, preprint, 2024, arXiv:2401.00002.",
                "identified_by": "declared",
            },
            {
                "work": "doi:10.4171/synth.0003",
                "citekey": "third",
                "text": "J. Ibarra, Foundations of the synthetic period map, Lecture notes, 1998.",
                "identified_by": "lookup",
            },
        ],
        "versions": [
            {
                "id": "arxiv:2401.00001v1",
                "has_source": True,
                "has_pdf": False,
                "method": "",
                "numbering": "",
                "extracted_at": "",
            },
            {
                "id": "arxiv:2401.00001v2",
                "has_source": True,
                "has_pdf": False,
                "method": "",
                "numbering": "",
                "extracted_at": "",
            },
        ],
        "download": {
            "kind": "source",
            "from": "https://example.invalid/synthetic/2401.00001v2",
            "at": AT,
            "bytes": len(A_V2.encode()),
        },
        "open_pdf": "",
        "home": "arxiv/2401.00001",
    }


def _work_b() -> dict[str, Any]:
    return {
        "record": 1,
        "key": "arxiv:2401.00002",
        "ids": ["arxiv:2401.00002"],
        "title": "A vanishing theorem for weighted stable curves",
        "authors": ["Ekstrom, Fenna", "Gallant, Hollis"],
        "year": "2024",
        "msc": ["14N35"],
        "arxiv_category": "math.AG",
        "licence": "arXiv non-exclusive",
        "depth": 1,
        "reached_from": ["arxiv:2401.00001"],
        "reached_by": "declared",
        "provenance": "declared",
        "citekeys": ["other"],
        "references_known": True,
        "references": [
            {
                "work": "arxiv:2401.00001",
                "citekey": "other",
                "text": "B. Aurelio and D. Cerny, Tropical cycles on fans of valuated matroids, preprint, 2024, arXiv:2401.00001.",
                "identified_by": "declared",
            },
            {
                "work": "doi:10.4171/synth.0003",
                "citekey": "third",
                "text": "J. Ibarra, Foundations of the synthetic period map, Lecture notes, 1998.",
                "identified_by": "lookup",
            },
        ],
        "versions": [
            {
                "id": "arxiv:2401.00002v1",
                "has_source": True,
                "has_pdf": False,
                "method": "",
                "numbering": "",
                "extracted_at": "",
            },
        ],
        "download": {
            "kind": "source",
            "from": "https://example.invalid/synthetic/2401.00002v1",
            "at": AT,
            "bytes": len(B_V1.encode()),
        },
        "open_pdf": "",
        "home": "arxiv/2401.00002",
    }


def _work_c() -> dict[str, Any]:
    return {
        "record": 1,
        "key": "doi:10.4171/synth.0003",
        "ids": ["doi:10.4171/synth.0003"],
        "title": "Foundations of the synthetic period map",
        "authors": ["Ibarra, Juno"],
        "year": "1998",
        "msc": ["14D07"],
        "arxiv_category": "",
        "licence": "",
        "depth": 2,
        "reached_from": ["arxiv:2401.00001", "arxiv:2401.00002"],
        "reached_by": "lookup",
        "provenance": "resolved",
        "citekeys": ["third"],
        "references_known": False,
        "references": [],
        "versions": [
            {
                "id": "doi:10.4171/synth.0003",
                "has_source": False,
                "has_pdf": False,
                "method": "",
                "numbering": "",
                "extracted_at": "",
            },
        ],
        "download": {},
        "open_pdf": "",
        "home": "doi/10.4171_synth.0003",  # sanitised as identity.sanitise does, so one identifier is one directory
    }


# home -> version-local -> source, for the versions that have one.
SOURCES: dict[str, dict[str, str]] = {
    "arxiv/2401.00001": {"v1": A_V1, "v2": A_V2},
    "arxiv/2401.00002": {"v1": B_V1},
}


def write_corpus(dest: Path) -> Path:
    """Write the whole corpus into `dest`, replacing any `works/` already there so a rerun cannot leave a stale file behind.

    Parameters
    ----------
    dest : Path
        The corpus root to write; created if it is not there.

    Returns
    -------
    Path
        `dest`, for a caller that wants to hand it straight to `weft.config.load`.
    """
    dest.mkdir(parents=True, exist_ok=True)
    works = dest / "works"
    if works.exists():
        shutil.rmtree(works)
    _write(dest / "weft.toml", WEFT_TOML)
    _write(dest / "README.md", README)
    for record in (_work_a(), _work_b(), _work_c()):
        home = works / Path(str(record["home"]))
        home.mkdir(parents=True, exist_ok=True)
        _write(home / "work.json", json.dumps(record, indent=2, sort_keys=True, ensure_ascii=False) + "\n")
        for local, text in SOURCES.get(str(record["home"]), {}).items():
            _write(home / local / "src" / "main.tex", text)
    return dest


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def main(argv: list[str]) -> int:
    dest = Path(argv[1]).expanduser().resolve() if len(argv) > 1 else DEST
    write_corpus(dest)
    if dest == DEST:
        _write(DEST.parent / "README.md", DEMOS_README)
    print(f"wrote {dest}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
